name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Checks
      run: |
        echo checking files...
        npm run check
    - name: Install NPM packages
      run: npm ci
    - name: Transpile
      run: |
        echo transpiling...
        npm run build
    
